server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfe
    username: root
    password:
  jpa:
   database: mysql
    show: true
      hibernate:
        ddl_auto: create
logging:
  level:
      org.springframework.web: DEBUG
      ma.pfe: ERROR
      org.habernate: